
CREATE SCHEMA DOLPHIN;

go

create table DOLPHIN.CLIENTE_TEST(
	COD_CLIENTE INT NOT NULL IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(100),
	APELLIDO_PATERNO VARCHAR(100),
	APELLIDO_MATERNO VARCHAR(100),
	ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
)

INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('José', 'Peréz', 'Llanos');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Alan', 'Soriano', 'Ramos');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Ariana', 'Mejía', 'Luna');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Anjali', 'Ruíz', 'Lee');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Sandra', 'Vallejo', 'Rua');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Francisco', 'Sagasti', 'Huaman');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Matilde', 'Vizcarra', 'Huaman');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Oscar', 'Arteaga', 'Gonzalez');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Luis', 'Sol', 'Palillo');
INSERT INTO DOLPHIN.CLIENTE_TEST (NOMBRE,APELLIDO_PATERNO, APELLIDO_MATERNO ) VALUES('Yoselin', 'Benites', 'Mu');

update DOLPHIN.CLIENTE_TEST set ESTADO = 'INACTIVO' WHERE COD_CLIENTE = 10;
update DOLPHIN.CLIENTE_TEST set ESTADO = 'INACTIVO' WHERE COD_CLIENTE = 9;
update DOLPHIN.CLIENTE_TEST set ESTADO = 'INACTIVO' WHERE COD_CLIENTE = 8;
update DOLPHIN.CLIENTE_TEST set ESTADO = 'INACTIVO' WHERE COD_CLIENTE = 7;



/*********************************
Este procedimeitno alamcenado como parametro de entrada tiene el estado
Si el estado es igual a NULL => muetsra la lista sin importar los estados
Si el estado es igual a 'ACTIVO' => muetsra la lista de usuarios activos
Si el estado es igual a 'INACTIVO' => muetsra la lista de usuarios inactivos
**********************************/
create PROCEDURE DOLPHIN.[SP_PRUEBA_LISTA_CLIENTES] 
(
	@ESTADO VARCHAR(20)
)
AS
BEGIN

		SELECT 
		COD_CLIENTE as codigoCliente, 
		NOMBRE as nombre,
		APELLIDO_PATERNO as apellidoPaterno,
		APELLIDO_MATERNO as apellidoMaterno
		FROM DOLPHIN.CLIENTE_TEST CLI
		WHERE
		ESTADO = COALESCE(@ESTADO, ESTADO);	
END

-- Example
select * from DOLPHIN.CLIENTE_TEST

-- Execute Stored Procedure
exec DOLPHIN.[SP_PRUEBA_LISTA_CLIENTES] null

exec DOLPHIN.[SP_PRUEBA_LISTA_CLIENTES] 'ACTIVO'

exec DOLPHIN.[SP_PRUEBA_LISTA_CLIENTES] 'INACTIVO'
